version: 1
formatters:
  simple:
    format: '%(asctime)s.%(msecs)03d - %(levelname)s - %(name)s - %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  log_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: out/ndpcc.log
    mode: w
loggers:
  matplotlib:
    level: WARNING
    handlers: [log_file]
root:
  level: DEBUG
  handlers: [console, log_file]
